stages:
  - build

build-ios:
  stage: build
  tags:
    - saas-macos-medium-m1
  image: macos-15-xcode-16
  timeout: 2h
  script:
    - xcodebuild -version
    - cmake --version
    - make download
    - make contrib
    - make xcframework
    - ls -la dist/telephony.xcframework contrib/ios-arm64/lib
  artifacts:
    name: telephony-ios
    paths:
      - dist/telephony.xcframework
      - dist/headers
      - contrib/ios-arm64/lib/
      - contrib/ios-simulator-arm64/lib/
    expire_in: 30 days
