stages:
  - build

build-contrib:
  stage: build
  tags:
    - saas-macos-medium-m1
  image: macos-15-xcode-16
  timeout: 1h
  script:
    - make download
    - make contrib
    - ls -la contrib/fat/lib/
  artifacts:
    name: baresip-ios-contrib
    paths:
      - contrib/fat/lib/
    expire_in: 30 days
